# Use an official Node.js runtime as the base image
FROM node:18

# Install necessary dependencies for Puppeteer
RUN apt-get update && apt-get install gnupg wget -y && \
  wget --quiet --output-document=- https://dl-ssl.google.com/linux/linux_signing_key.pub | gpg --dearmor > /etc/apt/trusted.gpg.d/google-archive.gpg && \
  sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' && \
  apt-get update && \
  apt-get install google-chrome-stable -y --no-install-recommends && \
  rm -rf /var/lib/apt/lists/*

# Create a non-root user to use if we're running as root
RUN useradd --create-home puppeteer

# Set the working directory in the container to /app
WORKDIR /app

# Change the ownership of the /app directory to puppeteer
RUN chown -R puppeteer:puppeteer /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install the application dependencies
RUN npm install

# Copy the rest of the application code to the working directory
COPY . .

# Expose port 3000 for the application
EXPOSE 8000

# Switch to the non-root user
USER puppeteer

# Define the command to run the application
CMD npm run dev